In [1]:
import numpy as np
np.__version__

'1.21.5'

In [19]:
# Szereg

list_numbers = [1,2,3]

In [3]:
list_everything = [1, False, "Some random string"]

In [6]:
np.array([1,2,"1"])

array(['1', '2', '1'], dtype='<U11')

In [7]:
classic_list = [1, 2, 3, 5, 7, 11]
type(classic_list)

list

In [8]:
numpy_array = np.array(classic_list)
type(numpy_array)

numpy.ndarray

In [9]:
numpy_array.shape

(6,)

In [11]:
np.array([2,4]).mean()

3.0

In [18]:
# Macierz

In [15]:
numpy_matrix = np.array([[1,2,3], [5,7,11]])
numpy_matrix.shape

(2, 3)

In [16]:
matrix1 = np.array([
	[1,2,3],
	[4,5,6],
	[7,8,9]
])

In [17]:
#możemy pobrać pierwszy wiersz takim indeksowaniem
matrix1[0, :]

array([1, 2, 3])

In [21]:
# a ostatnia kolumna to
matrix1[:, -1]

array([3, 6, 9])

In [24]:
# Operacje
# Po pierwsze możemy sumować, uśredniać macierze jako całość, ale też wybierać określone wiersze czy kolumny.

In [26]:
# Dajmy taką macierz:
matrix2 = np.array([
	[1,2,3],
	[0,8,10],
	[1,10,12]
])

In [27]:
matrix2.sum()

47

In [28]:
# Chcielibyśmy jednak wejść nieco głębiej i zadać pytanie – jakie sumy mają całe wiersze i kolumny? 
# Wtedy należy dodać parametr axis do danej metody statystycznej, np. sum. Pamiętaj, że w tym konkretnym przypadku 0 jako wartość argumentu axis to kolumny, a 1 to wiersze.
# Oczywiście, nie obawiaj się, 
# nawet jeśli zapomnisz, to zawsze możesz użyć Jupytera albo IPythona do krótkiego testu, by się upewnić.

In [29]:
# sumując kolumny, otrzymamy tutaj:
matrix2.sum(axis=0)

array([ 2, 20, 25])

In [30]:
# sumując wiersze
matrix2.sum(axis=1)

array([ 6, 18, 23])

In [31]:
# Podstawowe zadanie to dodawanie wektorów. Wykonywane jest ono z użyciem operatora +.
np.array([1,2]) + np.array([8,9])

array([ 9, 11])

In [32]:
#  dodawać i mnożyć macierze.
np.array([
	[1,2],
	[3,4]
]) + \
np.array([
	[8,9],
	[10,11]
])

array([[ 9, 11],
       [13, 15]])

In [33]:
#  Dostępny jest też tzw. iloczyn skalarny (ang. dot product).
np.array([
	[1,2],
	[3,4]
]).dot([1,1])

array([3, 7])